<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TravelPlanner</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Update="app\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="2.4.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
  </ItemGroup>
</Project>
